from sqlalchemy.orm import Session
from sqlalchemy import desc
from datetime import datetime
from typing import List, Optional

from ..models import Complaint, StatusHistory
from ..schemas import ComplaintCreate

# --------------------------------------------------------------------------------
# COMPLAINT MANAGER
# This file contains all the "business logic" for complaints. It handles saving them,
# retrieving them, and updating their status in the database. 
# --------------------------------------------------------------------------------

class ComplaintManager:
    
    @staticmethod
    def create_complaint(db: Session, complaint_data: ComplaintCreate, ai_result: dict) -> Complaint:
        # Create a new SQLAlchemy Complaint object using the data from the citizen
        # and the results generated by the AIAnalyzer.
        new_complaint = Complaint(
            description=complaint_data.description,
            location=complaint_data.location,
            citizen_contact=complaint_data.citizen_contact,
            # AI fields
            category=ai_result.get("category", "Uncategorized"),
            priority=ai_result.get("priority", "Medium"),
            ai_summary=ai_result.get("summary", ""),
            ai_confidence=ai_result.get("confidence", 0.0)
        )
        
        # Add the new complaint to our database session
        db.add(new_complaint)
        # Commit the transaction so it's permanently saved to the disk
        db.commit()
        # Refresh the object so it pulls the newly generated 'complaint_id' and 'created_at' from the DB
        db.refresh(new_complaint)
        
        # Every new complaint gets an initial status history entry marking it as "Open"
        history_entry = StatusHistory(
            complaint_id=new_complaint.complaint_id,
            old_status="None",
            new_status="Open",
            changed_by="System"
        )
        db.add(history_entry)
        db.commit()
        
        return new_complaint

    @staticmethod
    def get_complaint(db: Session, complaint_id: str) -> Optional[Complaint]:
        # Simple lookup: find the first complaint where the ID matches
        return db.query(Complaint).filter(Complaint.complaint_id == complaint_id).first()

    @staticmethod
    def list_complaints(db: Session, 
                        category: Optional[str] = None, 
                        priority: Optional[str] = None, 
                        status: Optional[str] = None,
                        department: Optional[str] = None) -> List[Complaint]:
        
        # Start a query for all complaints
        query = db.query(Complaint)
        
        # If the admin asked to filter by a specific category, add that to the query
        if category:
            query = query.filter(Complaint.category == category)
            
        # Add priority filter if provided
        if priority:
            query = query.filter(Complaint.priority == priority)
            
        # Add status filter if provided (e.g., show only "Open" complaints)
        if status:
            query = query.filter(Complaint.status == status)
            
        # Add department filter if provided
        if department:
            query = query.filter(Complaint.assigned_department == department)
            
        # Sort them newest first (descending order of created_at)
        query = query.order_by(desc(Complaint.created_at))
        
        # Execute the query and return the list
        return query.all()

    @staticmethod
    def update_status(db: Session, complaint_id: str, new_status: str, changed_by: str) -> Optional[Complaint]:
        # First, find the complaint we want to update
        complaint = db.query(Complaint).filter(Complaint.complaint_id == complaint_id).first()
        
        # If it doesn't exist, return None so the router can throw a 404 error
        if not complaint:
            return None
            
        old_status = complaint.status
        
        # If the status isn't actually changing, don't do anything
        if old_status == new_status:
            return complaint
            
        # Update the main complaint record
        complaint.status = new_status
        
        # If the new status is "Resolved", we must record the exact time it happened.
        # This is critical for our resolution-time statistics.
        if new_status == "Resolved":
            complaint.resolved_at = datetime.utcnow()
        elif old_status == "Resolved" and new_status != "Resolved":
            # If it's being re-opened, clear the resolved_at time
            complaint.resolved_at = None
            
        # Create an audit log entry in the StatusHistory table
        history_entry = StatusHistory(
            complaint_id=complaint.complaint_id,
            old_status=old_status,
            new_status=new_status,
            changed_by=changed_by
        )
        
        db.add(history_entry)
        db.commit()
        db.refresh(complaint)
        
        return complaint

    @staticmethod
    def assign_department(db: Session, complaint_id: str, department: str, assigned_by: str) -> Optional[Complaint]:
        # Find the complaint
        complaint = db.query(Complaint).filter(Complaint.complaint_id == complaint_id).first()
        
        if not complaint:
            return None
            
        # Assign the new department
        complaint.assigned_department = department
        
        # If the complaint was just sitting "Open", automatically move it to "Assigned"
        # to save the admin a click.
        if complaint.status == "Open":
            ComplaintManager.update_status(db, complaint_id, "Assigned", assigned_by)
        else:
            # Otherwise, just save the department change
            db.commit()
            db.refresh(complaint)
            
        return complaint
