# We import the base classes needed to describe a database table using Python code
from sqlalchemy import Column, String, Text, Float, DateTime, ForeignKey
# We import relationship to link tables together (e.g., a Complaint has many StatusHistories)
from sqlalchemy.orm import relationship
import uuid
from datetime import datetime

# We import the shared Base class we set up in database.py
from .database import Base

# --------------------------------------------------------------------------------
# COMPLAINT MODEL
# This table stores the actual civic complaints submitted by citizens.
# --------------------------------------------------------------------------------
class Complaint(Base):
    # This tells SQLAlchemy to name the table "complaints" in the database
    __tablename__ = "complaints"

    # complaint_id: The unique identifier for each complaint. 
    # We use a UUID (a long random string) instead of a regular number (1, 2, 3) 
    # so it's harder for people to guess other citizens' tracking IDs.
    complaint_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # description: The full, original text written by the citizen.
    # Stored as Text because it could be quite long.
    description = Column(Text, nullable=False)
    
    # category: The AI-assigned bucket for this issue (e.g., "Road", "Water/Drainage").
    # It starts as "Uncategorized" in case the AI fails.
    category = Column(String, default="Uncategorized")
    
    # priority: The AI-assigned urgency (Low, Medium, High, Critical).
    # Default is "Medium" as a safe middle ground.
    priority = Column(String, default="Medium")
    
    # ai_summary: A short, actionable summary generated by the AI for quick reading by admins.
    ai_summary = Column(Text, nullable=True)
    
    # ai_confidence: A score from 0.0 to 1.0 indicating how sure the AI was about its classification.
    # This helps admins know if they should double-check the AI's work.
    ai_confidence = Column(Float, nullable=True)
    
    # location: Where the problem is. Can be free text ("Main St") or coordinates.
    location = Column(String, nullable=False)
    
    # image_path: The file path to an optional photo uploaded by the citizen.
    # Nullable because not everyone will upload a picture.
    image_path = Column(String, nullable=True)
    
    # status: The current state of the complaint (Open, Assigned, In Progress, Resolved).
    # Every new complaint starts as "Open".
    status = Column(String, default="Open")
    
    # assigned_department: Which team is responsible for fixing this (e.g., "Water Dept").
    # Nullable because it hasn't been assigned yet when first created.
    assigned_department = Column(String, nullable=True)
    
    # citizen_contact: Optional email or phone number for updates.
    citizen_contact = Column(String, nullable=True)
    
    # created_at: The exact timestamp when the citizen clicked submit.
    # 'default=datetime.utcnow' automatically fills this in at creation time.
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # updated_at: The timestamp of the last change made to this complaint.
    # 'onupdate=datetime.utcnow' automatically changes this whenever the row is modified.
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # resolved_at: The exact time the status changed to "Resolved".
    # This is crucial for calculating our resolution-time statistics later.
    resolved_at = Column(DateTime, nullable=True)

    # Link to the StatusHistory table. This allows us to easily get all past status changes
    # for a specific complaint by accessing `complaint.history`.
    history = relationship("StatusHistory", back_populates="complaint")


# --------------------------------------------------------------------------------
# STATUS HISTORY MODEL
# This table keeps an audit trail. Every time a complaint's status changes 
# (e.g., from "Open" to "In Progress"), we record a row here.
# --------------------------------------------------------------------------------
class StatusHistory(Base):
    __tablename__ = "status_history"

    # A simple numeric ID for each log entry
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # A foreign key linking this history record to a specific complaint.
    # This tells the database "this record belongs to the complaint with this ID".
    complaint_id = Column(String, ForeignKey("complaints.complaint_id"))
    
    # The previous state before the change occurred
    old_status = Column(String, nullable=False)
    
    # The new state after the change
    new_status = Column(String, nullable=False)
    
    # When this change happened
    changed_at = Column(DateTime, default=datetime.utcnow)
    
    # Who made the change (usually the username of the admin)
    changed_by = Column(String, nullable=False)

    # Relationship linking back to the parent Complaint object
    complaint = relationship("Complaint", back_populates="history")


# --------------------------------------------------------------------------------
# ADMIN MODEL
# This table stores the login credentials for city staff using the dashboard.
# --------------------------------------------------------------------------------
class Admin(Base):
    __tablename__ = "admins"

    # A simple numeric ID for the admin user
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # The login name. 'unique=True' ensures no two admins can have the same username.
    username = Column(String, unique=True, index=True, nullable=False)
    
    # We NEVER store plain text passwords. This stores a cryptographically scrambled
    # version of the password (a hash) created by bcrypt.
    hashed_password = Column(String, nullable=False)
    
    # Role description (e.g., "SuperAdmin", "DepartmentLead"). 
    # Hardcoded to "Admin" for this project's simple requirements.
    role = Column(String, default="Admin")
    
    # When this admin account was created
    created_at = Column(DateTime, default=datetime.utcnow)
